# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# HAVE_LLVM_LIBCPP_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HAVE_LLVM_LIBCPP_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The HAVE_LLVM_LIBCPP_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/mato/projects/rumpkernel/mysql/mysql-5.6.23/build-cross/CMakeFiles/CMakeTmp/src.cxx
# Executable    : /home/mato/projects/rumpkernel/mysql/mysql-5.6.23/build-cross/CMakeFiles/cmTryCompileExec8117161-HAVE_LLVM_LIBCPP_EXITCODE
# Run arguments : 
#    Called from: [2]	/home/mato/projects/rumpkernel/mysql/mysql-5.6.23/configure.cmake
#                 [1]	/home/mato/projects/rumpkernel/mysql/mysql-5.6.23/CMakeLists.txt

SET( HAVE_LLVM_LIBCPP_EXITCODE 
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_SIGWAIT
     "1"
     CACHE STRING "Have sigwait()" FORCE)
